#ifndef MOCASINNS_PARALLEL_TEMPERING_INVERSE_TEMPERATURE_OPTIMIZATION_HPP
#define MOCASINNS_PARALLEL_TEMPERING_INVERSE_TEMPERATURE_OPTIMIZATION_HPP

#include "inverse_temperature_optimization_equal_acceptance_probabilities.hpp"
#include "inverse_temperature_optimization_katzgraber.hpp"

#endif
